// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

// AnalyticsServ is an autogenerated mock type for the AnalyticsServ type
type AnalyticsServ struct {
	mock.Mock
}

// SendEvent provides a mock function with given fields: ctx, name, date
func (_m *AnalyticsServ) SendEvent(ctx context.Context, name string, date *timestamppb.Timestamp) error {
	ret := _m.Called(ctx, name, date)

	if len(ret) == 0 {
		panic("no return value specified for SendEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *timestamppb.Timestamp) error); ok {
		r0 = rf(ctx, name, date)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAnalyticsServ creates a new instance of AnalyticsServ. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnalyticsServ(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnalyticsServ {
	mock := &AnalyticsServ{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
