env: "local"
storage_path: "./storage/storage.db"
http_server:
  address: "0.0.0.0:8082"
  timeout: 4s
  idle_timeout: 30s
  user: "my_user"
  password: "my_pass"
clients:
  analytics:
    address: "analytics:44044" 